### ISSUE TITLE
Compress images, and minify the code

### ISSUE THREAD

**Issue by doriel** [oleoneto/EKLETIK-V1#1]
Always test your site on google PageSpeed to make it load faster. The site is taking to long to load due to uncompressed images(1 or 2MB images is too much for the web) and more as shown here (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fekletik.com%2F)...

**Comment by doriel** [comment]
And this is a big problem for us Angolan's because we have low speed internet.

**Comment by oleoneto** [comment]
Thanks for the tip. This is definitely the next step in our development before we officially launch the site. I am not very familiar with optimization, however, I'm willing to learn. I could use your help.

**Comment by doriel** [comment]
No problem bro...
